modLoader = "javafml"
loaderVersion = "${loader_range}"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = ""
displayURL = "https://www.curseforge.com/minecraft/mc-mods/re-avaritia"
logoFile = "logo.png"
authors = "${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${neo_range}"
ordering = "NONE" # NONE/BEFORE/AFTER
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_range}"
ordering = "NONE"
side = "BOTH"
